### ISSUE TITLE
uncaughtException in localhost

### ISSUE THREAD

**Issue by mayilvagananarjun** [joeblau/gitignore.io#168]
I was trying to run this locally and got the following error message. Unable to figure out the issue.
```
Server listening on http://localhost:8000
Application ready to serve requests.
Environment: development
Fri, 15 Jan 2016 03:36:24 GMT uncaughtException ENOENT: no such file or directory, open '/Users/arjunmayilvaganan/Code/personal-project/gitignore.io/models/../data/custom/AppCode.gitignore'
Error: ENOENT: no such file or directory, open '/Users/arjunmayilvaganan/Code/personal-project/gitignore.io/models/../data/custom/AppCode.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at /Users/arjunmayilvaganan/Code/personal-project/gitignore.io/models/datastore.js:32:31
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by joeblau** [comment]
Did you install the git submodules?

**Comment by mayilvagananarjun** [comment]
@joeblau,
Sorry. I'm not aware of that.
I did a `git submodule` and got an `alphanumeric data/gitignore`.
Then,
did an internet search and found that a git submodule can be added as follows and so did,
`git submodule add https://github.com/github/gitignore`.
The issue still remains.

**Comment by joeblau** [comment]
These are the steps you need to perform in this order.
```sh
git clone git@github.com:joeblau/gitignore.io.git
cd gitignore.io/
git submodule init
git submodule update
npm install
node server.js
```

**Comment by mayilvagananarjun** [comment]
@joeblau, Thank you so much.

**Comment by joeblau** [comment]
I've also updated the `README.md` to add these steps.

**Comment by mayilvagananarjun** [comment]
@joeblau, +1.
